on:
  push:
    branches:
      - main
  pull_request:

name: Unit Test
jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Test
        run: |
          npm install
          npm run test
